Install Docker on Ubuntu 20.04 LTS:
Update the apt package index:
sudo apt update

Install packages to allow apt to use a repository over HTTPS:
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common

Add Docker's official GPG key:
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

Add the Docker stable repository:
echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

Update the apt package index again:
sudo apt update

Install Docker:
sudo apt install -y docker-ce docker-ce-cli containerd.io

Add your user to the docker group to run Docker commands without sudo:
sudo usermod -aG docker $USER
Restart your system or log out and log back in to apply the group changes.

Install Docker Compose:
Download the Docker Compose binary:
sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

Apply execute permissions to the binary:
sudo chmod +x /usr/local/bin/docker-compose

Create a symbolic link to make it accessible globally:
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

Verify the installation:
docker-compose --version